# Site settings
title: RDMLA
email: 
description: >
 Research Data Management Library Academy: Exploring the need for a research data management librarian academy
url: "https://rdmla.github.io/home"

# Social links
twitter_username: #RDM
github_username:  RDMLA

# Build settings
markdown: kramdown
theme: minima
