# Site settings
title: RDMLA
email: 
description: >
 Research Data Management Librarian Academy: Exploring the need for research data management training for librarians
url: "https://rdmla.github.io/"

# Social links
github_username:  RDMLA
twitter_username: The_RDMLA
facebook_username: TheRDMLA

# Build settings
markdown: kramdown
theme: minima

# plugins
plugins:
  - jekyll-redirect-from
